[package]
name = "wpilib"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]
build = "build.rs"
description = "FRC's WPILib written in Rust."
# documentation = "..."
# homepage = "..."
repository = "https://github.com/Lytigas/first-rust-competition"
readme = "./README.md"
keywords = ["frc", "RoboRIO"]
categories = ["embedded", "hardware-support", "external-ffi-bindings"]
license = "GPL-3.0"

include = [
    "src/**/*",
    "Cargo.toml",
    "build.rs",
    "HAL/include/**/*",
    "HAL/lib/**/*",]
exclude = [".cargo", "./**/makefile"]

[lib]
name = "wpilib"
path = "src/lib.rs"
# Test can only be run on ARM
test = false


[dependencies]


[build-dependencies]
bindgen = "0.36.0"
